[2024-11-23T23:54:08.449+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T23:54:08.467+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_cdm_task.trigger_cdm_task manual__2024-11-23T23:54:07.031922+00:00 [queued]>
[2024-11-23T23:54:08.475+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_cdm_task.trigger_cdm_task manual__2024-11-23T23:54:07.031922+00:00 [queued]>
[2024-11-23T23:54:08.475+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-23T23:54:08.486+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): trigger_cdm_task> on 2024-11-23 23:54:07.031922+00:00
[2024-11-23T23:54:08.494+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=650) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-23T23:54:08.495+0000] {standard_task_runner.py:72} INFO - Started process 651 to run task
[2024-11-23T23:54:08.496+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'trigger_cdm_task', 'trigger_cdm_task', 'manual__2024-11-23T23:54:07.031922+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/cdm.py', '--cfg-path', '/tmp/tmpiwd7vlri']
[2024-11-23T23:54:08.497+0000] {standard_task_runner.py:105} INFO - Job 71: Subtask trigger_cdm_task
[2024-11-23T23:54:08.541+0000] {task_command.py:467} INFO - Running <TaskInstance: trigger_cdm_task.trigger_cdm_task manual__2024-11-23T23:54:07.031922+00:00 [running]> on host de82a0198583
[2024-11-23T23:54:08.614+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_cdm_task' AIRFLOW_CTX_TASK_ID='trigger_cdm_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T23:54:07.031922+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-23T23:54:07.031922+00:00'
[2024-11-23T23:54:08.614+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T23:54:12.106+0000] {logging_mixin.py:190} INFO - 400
[2024-11-23T23:54:12.106+0000] {logging_mixin.py:190} INFO - 40c0d983e6eca67216fb0d6f775155f9
[2024-11-23T23:54:12.106+0000] {logging_mixin.py:190} INFO - CDM.0001
[2024-11-23T23:54:12.106+0000] {logging_mixin.py:190} INFO - The resource does not exist or is illegal, Please contact technical support for assistance!
[2024-11-23T23:54:12.107+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-23T23:54:12.117+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T23:54:12.118+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=trigger_cdm_task, task_id=trigger_cdm_task, run_id=manual__2024-11-23T23:54:07.031922+00:00, execution_date=20241123T235407, start_date=20241123T235408, end_date=20241123T235412
[2024-11-23T23:54:12.163+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-23T23:54:12.182+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T23:54:12.183+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
