[2024-11-23T22:26:11.884+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T22:26:11.899+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_bucket.save_date manual__2024-11-23T22:26:10.341405+00:00 [queued]>
[2024-11-23T22:26:11.907+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_bucket.save_date manual__2024-11-23T22:26:10.341405+00:00 [queued]>
[2024-11-23T22:26:11.907+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-23T22:26:11.918+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_date> on 2024-11-23 22:26:10.341405+00:00
[2024-11-23T22:26:11.926+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=186) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-23T22:26:11.927+0000] {standard_task_runner.py:72} INFO - Started process 188 to run task
[2024-11-23T22:26:11.928+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'create_bucket', 'save_date', 'manual__2024-11-23T22:26:10.341405+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/obs.py', '--cfg-path', '/tmp/tmp1r9g4znc']
[2024-11-23T22:26:11.929+0000] {standard_task_runner.py:105} INFO - Job 49: Subtask save_date
[2024-11-23T22:26:11.972+0000] {task_command.py:467} INFO - Running <TaskInstance: create_bucket.save_date manual__2024-11-23T22:26:10.341405+00:00 [running]> on host d67e2d2d9b67
[2024-11-23T22:26:12.054+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_bucket' AIRFLOW_CTX_TASK_ID='save_date' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T22:26:10.341405+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-23T22:26:10.341405+00:00'
[2024-11-23T22:26:12.054+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T22:26:30.053+0000] {logging_mixin.py:190} INFO - Create Bucket Failed_4
[2024-11-23T22:26:30.054+0000] {logging_mixin.py:190} INFO - requestId: 000001935B22396747CEF1B8F19C2C64
[2024-11-23T22:26:30.054+0000] {logging_mixin.py:190} INFO - errorCode: UserRestricted
[2024-11-23T22:26:30.054+0000] {logging_mixin.py:190} INFO - errorMessage: This operation is forbidden for restricted users
[2024-11-23T22:26:30.054+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-23T22:26:30.066+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T22:26:30.066+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=create_bucket, task_id=save_date, run_id=manual__2024-11-23T22:26:10.341405+00:00, execution_date=20241123T222610, start_date=20241123T222611, end_date=20241123T222630
[2024-11-23T22:26:30.120+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-23T22:26:30.135+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T22:26:30.136+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
