[2024-11-24T00:00:03.166+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-24T00:00:03.186+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.check_file_exists scheduled__2024-11-23T00:00:00+00:00 [queued]>
[2024-11-24T00:00:03.194+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.check_file_exists scheduled__2024-11-23T00:00:00+00:00 [queued]>
[2024-11-24T00:00:03.195+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2024-11-24T00:00:03.207+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): check_file_exists> on 2024-11-23 00:00:00+00:00
[2024-11-24T00:00:03.215+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=725) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-24T00:00:03.217+0000] {standard_task_runner.py:72} INFO - Started process 726 to run task
[2024-11-24T00:00:03.218+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'check_file_exists', 'scheduled__2024-11-23T00:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp_ecnc63m']
[2024-11-24T00:00:03.219+0000] {standard_task_runner.py:105} INFO - Job 75: Subtask check_file_exists
[2024-11-24T00:00:03.269+0000] {task_command.py:467} INFO - Running <TaskInstance: my_dag.check_file_exists scheduled__2024-11-23T00:00:00+00:00 [running]> on host 799b59ba20e9
[2024-11-24T00:00:03.358+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='check_file_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-23T00:00:00+00:00'
[2024-11-24T00:00:03.359+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-24T00:00:03.373+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-24T00:00:03.374+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Checking data..."']
[2024-11-24T00:00:03.390+0000] {subprocess.py:99} INFO - Output:
[2024-11-24T00:00:03.391+0000] {subprocess.py:106} INFO - Checking data...
[2024-11-24T00:00:03.392+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-11-24T00:00:03.420+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-24T00:00:03.421+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=check_file_exists, run_id=scheduled__2024-11-23T00:00:00+00:00, execution_date=20241123T000000, start_date=20241124T000003, end_date=20241124T000003
[2024-11-24T00:00:03.472+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-24T00:00:03.492+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-24T00:00:03.493+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
